const products = [
  {
    id: 1,
    name: "Rau cải xanh hữu cơ",
    category: "Rau",
    brand: "VinEco",
    seller: "Nông trại A",
    city: "Hà Nội",
    price: 15000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Cà chua Đà Lạt",
    category: "Rau",
    brand: "Dalat Farm",
    seller: "Nông trại B",
    city: "Đà Lạt",
    price: 20000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Táo Mỹ nhập khẩu",
    category: "Trái cây",
    brand: "Organic Việt",
    seller: "Nông trại C",
    city: "TP.HCM",
    price: 60000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Cam sành miền Tây",
    category: "Trái cây",
    brand: "TH",
    seller: "Nông trại D",
    city: "Cần Thơ",
    price: 35000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Thịt heo sạch",
    category: "Thịt",
    brand: "Satra",
    seller: "Trang trại E",
    city: "Hồ Chí Minh",
    price: 95000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Trứng gà ta",
    category: "Trứng",
    brand: "TH",
    seller: "Trang trại F",
    city: "Hà Nội",
    price: 30000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Dưa leo hữu cơ",
    category: "Rau",
    brand: "VinEco",
    seller: "Nông trại A",
    city: "Hà Nội",
    price: 12000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Chuối tây",
    category: "Trái cây",
    brand: "Organic Việt",
    seller: "Nông trại C",
    city: "TP.HCM",
    price: 25000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "Khoai tây sạch",
    category: "Rau",
    brand: "Dalat Farm",
    seller: "Nông trại B",
    city: "Lâm Đồng",
    price: 18000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Trứng vịt lộn",
    category: "Trứng",
    brand: "Satra",
    seller: "Trang trại G",
    city: "Cần Thơ",
    price: 10000,
    image: "https://via.placeholder.com/150",
  },
];

export default products;
